version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          BUNDLER_VERSION: 2.0.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.1
            bundle install
            apt-get update
            apt-get install postgresql
            postgres createuser test
            postgres createdb lahaus_api_test
            rails db:create
            rails db:migrate
      - ruby/bundle-install
      - run: rails test

