version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          BUNDLER_VERSION: 2.0.1
      - image: circleci/postgres:10.14
        environment:
          ALLOW_EMPTY_PASSWORD=yes
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.1
            bundle install
      - ruby/bundle-install
      - run: rails test

